### ISSUE TITLE
po/Makefile.in.in not found error

### ISSUE THREAD

**Issue by GvMariani** [tim-janik/rapicorn#10]
After working around the Issues #8 and #9, by patching the libpng support and using the tarball from git, still the build fails at the configure time, because it does not find the file "Makefile.in.in" in the "po" source directory:
***************
config.status: creating Makefile
config.status: creating po-helper.sh
config.status: error: cannot find input file: `po/Makefile.in.in'
error: Bad exit status from /home/giovanni/rpm/tmp/rpm-tmp.78717 (%build)
***************

In the above directory there is only a "Makefile.intltool": copying it to the desired name makes the build to proceed a little more.

**Comment by tim-janik** [comment]
The Git sources are provided for developers, e.g. autogen.sh needs to be called to build those. The .travis.yml file gives perfect instructions how to build the develop sources. If you're just building/packaging up Rapicorn for a distribution, please use the release tarballs available here: 
  https://testbit.eu/pub/dists/rapicorn/
These only require:
  configure && make && make install
And you can check for a successful build with
  make check installcheck
(Feel free to reopen if the problem persists with the release tarball.)
