### ISSUE TITLE
No configure test for pandoc

### ISSUE THREAD

**Issue by GvMariani** [tim-janik/rapicorn#11]
Rosa Linux ATM does not package pandoc, however rapicorn seems to need it:
******************
+ /usr/bin/make -j4
/usr/bin/make  all-recursive
make[1]: Entering directory '/tmp/abf/rpmbuild/BUILD/rapicorn-16.0.0'
Making all in .
make[2]: Entering directory '/tmp/abf/rpmbuild/BUILD/rapicorn-16.0.0'
  GEN      README
cd . && /bin/sh ./config.status --file=rapicorn.pc:rapicorn.pc.in
  GEN      ChangeLog
make[2]: pandoc: Command not found
Makefile:1253: recipe for target 'README' failed
make[2]: *** [README] Error 127
make[2]: *** Waiting for unfinished jobs....
config.status: creating rapicorn.pc
config.status: WARNING:  'rapicorn.pc.in' seems to ignore the --datarootdir setting
make[2]: Leaving directory '/tmp/abf/rpmbuild/BUILD/rapicorn-16.0.0'
Makefile:706: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/abf/rpmbuild/BUILD/rapicorn-16.0.0'
Makefile:572: recipe for target 'all' failed
make: *** [all] Error 2
error: Bad exit status from /home/giovanni/rpm/tmp/rpm-tmp.47615 (%build)
******************

It would be a good thing to test in configure for the presence of all the software needed to do a successful build...

**Comment by tim-janik** [comment]
Yes, we happily take patches ;-)
Btw, I'd be happy to integrate RPM test builds into our travis setup (docker based) once you got working RPM build instructions for me.

**Comment by GvMariani** [comment]
I'm very little fond of the autotools intricacies, but is something as the snippet below enough?
*******************************
dnl Check for pandoc
AC_CHECK_PROG(HAVE_PANDOC, pandoc, true, false)
if test "x$HAVE_PANDOC" = "xfalse"; then
	AC_MSG_ERROR([*** Pandoc is needed by Rapicorn])
fi
*********************************

**Comment by GvMariani** [comment]
> Btw, I'd be happy to integrate RPM test builds into our travis setup (docker based) once you got working RPM build instructions for me.
I don't know much about docker and travis, but I guess you're already familiar with things as:
https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide
http://www.rpm.org/max-rpm
If so, I can share and comment the .spec file I'm using to instruct the rpm build-system to do a rapicorn build: perhaps you can figure how to translate for your build setup...

**Comment by GvMariani** [comment]
I tested the snipped above with rapicorn 16.0.0 sources and it works:
ie makes the configure pass to fail with a message when pandoc is not installed...

**Comment by tim-janik** [comment]
Commit a2b3a69c649f5c9008f8e8b74e6d70d615d1324e (and previous ones) properly check for pandoc now. Thanks for your input.
