### ISSUE TITLE
Missing functional include in aidasignal.hh ?

### ISSUE THREAD

**Issue by ngeiswei** [tim-janik/rapicorn#15]
It seems `#include <functional>` is missing in aidasignal.hh, otherwise I'm getting a series of errors like bind is not a member of std, etc.

**Comment by ngeiswei** [comment]
For info my system is Ubuntu Studio 17.10 with gcc 7.2.0.

**Comment by tim-janik** [comment]
Thanks for the report, but we're not working on librapicorn anylonger, since there's now a 0.12.0 release of Beast that doesn't depend on rapicorn.
