### ISSUE TITLE
autogen/configure fails when python3 is default

### ISSUE THREAD

**Issue by milkmiruku** [tim-janik/rapicorn#5]
On Arch Linux with Python 2.7 and 3.5 installed.

> checking for RAPICORN_CORE... yes
> checking for a Python interpreter with version >= 2.7... python
> checking for python... /usr/bin/python
> checking for python version... 3.5
> checking for python platform... linux
> checking for python script directory... ${prefix}/lib/python3.5/site-packages
> checking for python extension module directory... ${exec_prefix}/lib/python3.5/site-packages
> checking for python3.5... (cached) /usr/bin/python
> checking for a version of Python >= '2.1.0'... yes
> checking for a version of Python >= 2.7... Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> TypeError: unorderable types: str() >= float()
> no
> configure: error: this package requires Python >= 2.7.
> If you have it installed, but it isn't the default Python
> interpreter in your system path, please pass the PYTHON_VERSION
> variable to configure. See ``configure --help'' for reference.

`./configure PYTHON=/usr/bin/python2.7` resolves the problem.

**Comment by milkmiruku** [comment]
And on `make`;

>   File "../aidacc/xmanifold.py", line 68
>     print 'Usage: xmanifold.py [-S] <filename> [maxcount]'
>                                                          ^
> SyntaxError: Missing parentheses in call to 'print'
> Makefile:1319: recipe for target 'aidavariants.hh' failed

Changing the `aidacc/xmanifold.py` shebang to python2.7 works.

**Comment by tim-janik** [comment]
Note, the failing configure check is implemented as
  AC_PYTHON_DEVEL([>= 2.7])
If that fails to detect python2 if python3 is the default, AFAICS the macro AC_PYTHON_DEVEL needs fixing, i.e. http://www.gnu.org/software/autoconf-archive/ax_python_devel.html
