### ISSUE TITLE
Libpng 1.6..x not detected even if present in the system

### ISSUE THREAD

**Issue by GvMariani** [tim-janik/rapicorn#8]
Trying to package rapicorn 16.0.0 for Rosa Linux Fresh R5 (a Mandriva heir) on x86_64.
As-is the released tarball does not build: it stops at configure time and complains about libpng >= 1.2 not found (but I have installed the release 1.6.16).

*******
checking for libpng12... no
configure: error: PNG image library libpng (>= 1.2) is missing, but required
error: Bad exit status from /home/giovanni/rpm/tmp/rpm-tmp.47512 (%build)
*******

The culprits are in configure.ac:
*********************
dnl --- require libpng ---
    if test -z "$LIBPNG"; then
	dnl # png_set_add_alpha() exists only since libpng v1.2
	AC_MSG_CHECKING(for libpng12)
	if $PKG_CONFIG --exists libpng12 ; then
	    AC_MSG_RESULT(yes)
	    LIBPNG=`$PKG_CONFIG --libs libpng12`
	elif $PKG_CONFIG --exists libpng13 ; then
	    AC_MSG_RESULT(yes)
	    LIBPNG=`$PKG_CONFIG --libs libpng13`
	else
	    AC_MSG_RESULT(no)
	    AC_MSG_ERROR([PNG image library libpng (>= 1.2) is missing, but required])
	fi
    fi
*********************
and in configure:
*********************
  if test -z "$LIBPNG"; then
           { $as_echo "$as_me:${as_lineno-$LINENO}: checking for libpng12" >&5
$as_echo_n "checking for libpng12... " >&6; }
	if $PKG_CONFIG --exists libpng12 ; then
	    { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
	    LIBPNG=`$PKG_CONFIG --libs libpng12`
	elif $PKG_CONFIG --exists libpng13 ; then
	    { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
	    LIBPNG=`$PKG_CONFIG --libs libpng13`
	else
	    { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }
	    as_fn_error $? "PNG image library libpng (>= 1.2) is missing, but required" "$LINENO" 5
	fi
    fi
*********************

Both the snippets test explicitly for libpng12 or libpng13, but they really should test for "libpng"...
On my system (libpng 1.6), beside the "regular" libpng16.pc, there is a "generic" libpng.pc file pointing to the correct library.

BTW, to use a more recent libpng, some more little changes are needed in the ui/pixmap.cc file, to accommodate changed interfaces (patch to correct all the issues attached).
[rapicorn-16.0.0-libpng.txt](https://github.com/tim-janik/rapicorn/files/223831/rapicorn-16.0.0-libpng.txt)

This is only the first issue I found, trying to resolve it led to some more (stay tuned...).

**Comment by tim-janik** [comment]
Commits 9cd1fccfa35621b3316ecf65a6ac153d0baf5b68 ff fixed up libpng support. Thanks for your input.
