### ISSUE TITLE
Missing .m4 files from the released tarball for 16.0.0

### ISSUE THREAD

**Issue by GvMariani** [tim-janik/rapicorn#9]
To resolve the Issue #8, it was needed to patch configure.ac (and configure); this usually requires also to regenerate the configure script.
However, with the tarball from https://testbit.eu/pub/dists/rapicorn/, the autoreconf pass fails at the very start, because acrapicorn.m4 and ld-symbolic.m4 are missing:
*******************
+ cd rapicorn-16.0.0
+ '[' 1 -eq 1 ']'
+ '[' 1 -eq 1 ']'
+ autoreconf -vfi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
/usr/bin/m4:configure.ac:3: cannot open `acrapicorn.m4': No such file or directory
/usr/bin/m4:configure.ac:4: cannot open `ld-symbolic.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
error: Bad exit status from /home/giovanni/rpm/tmp/rpm-tmp.33491 (%build)
*******************

Also, trying to be clever and to workaround the problem by patching configure without regenerating it, it does not work; in this case the build fails at the very start of the make phase:
**************************
+ /usr/bin/make -j4
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /tmp/abf/rpmbuild/BUILD/rapicorn-16.0.0/missing aclocal-1.15 
/usr/bin/m4:configure.ac:3: cannot open `acrapicorn.m4': No such file or directory
/usr/bin/m4:configure.ac:4: cannot open `ld-symbolic.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal-1.15: error: echo failed with exit status: 1
Makefile:607: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 1
error: Bad exit status from /home/giovanni/rpm/tmp/rpm-tmp.41166 (%build)
**************************

The tarball provided by GitHub release page, however, has all the needed files.

**Comment by tim-janik** [comment]
Hey GvMariani, regenerating the release tarball configure script from just the release tarball isn't really supported. We simply generate it from the Git sources via autogen.sh, a full build and make distcheck. If you want to patch configure.ac, you need to apply that to the checked out git sources and build the tarball similar to our travis builds. I'll quote the relevant bits from .travis.docker for you:

  nice ./autogen.sh --prefix=/usr --enable-devel-mode=no
  nice make -j`nproc`
  nice make check
  nice make install
  nice make installcheck
  nice make distcheck

I'll look into applying a fix for #8 next.

**Comment by GvMariani** [comment]
Thank you for your kindly reply...
Well, I don't know about too many projects, but usually I found that is OK to regenerate the configure script from the release tarballs, if needed, with a simple "autoreconf -vfi".
With rapicorn it is not the case, but my way to solve issue #8 required patching configure.ac (and consequently regenerating configure), and I guessed wrong...
